source 'https://github.com/Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Lego' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod 'Mediator', :git => 'https://github.com/Limon-O-O/Mediator.git', :branch => "master"

    # Tower
    pod "Mediator+Tower", :path => "../Mediator+Tower"
    pod "Tower", :path => "../Tower"

    # Door
    pod "Mediator+Door", :path => "../Mediator+Door"
    pod "Door", :path => "../Door"

    # Me
    pod "Mediator+Me"#, :path => "../Mediator+Me"
    pod "Me"#, :path => "../Me"

    # Door
    pod "Mediator+Profile", :path => "../Mediator+Profile"
    pod "Profile", :path => "../Profile"

    pod "Networking", :path => "../../Frameworks/Networking"
    pod "EggKit", :path => "../../Frameworks/EggKit"
    pod "LegoKit", :path => "../../Frameworks/LegoKit"

end
