source 'git@github.com:Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'LegoKit' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod 'RxSwift'

    pod "EggKit", :path => "../EggKit"

end
