source 'git@github.com:Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Me' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod "EggKit", :path => "../../Frameworks/EggKit"
    pod "LegoKit", :path => "../../Frameworks/LegoKit"
end
