source 'git@github.com:Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'MoyaSugar_Example' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod 'Moya/RxSwift'

    target 'MoyaSugar_Tests' do
    	inherit! :search_paths
  	end

end
