source 'https://github.com/Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Tower' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod "Mediator+Door", :path => "../Mediator+Door"
    pod "LegoContext", :path => "../../Frameworks/LegoContext"

end
