source 'https://github.com/Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Door' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod "Networking", :path => "../../Frameworks/Networking"
    pod "EggKit", :path => "../../Frameworks/EggKit"
    pod "LegoKit", :path => "../../Frameworks/LegoKit"
    pod "LegoContext", :path => "../../Frameworks/LegoContext"
    pod "Router", :path => "../../Frameworks/Router"

    pod 'MonkeyKing'

    pod 'RxSwift'
    pod 'RxCocoa'

end
