source '__SpecsRepo__'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target '${POD_NAME}_Example' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod '${POD_NAME}', :path => '../'

    target '${POD_NAME}_Tests' do
    	inherit! :search_paths

    	${INCLUDED_PODS}
  	end

end
