source 'git@github.com:Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'Tower_Example' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod "Mediator_Door", :path => "../../Mediator_Door"
    pod "LegoContext", :path => "../../../Frameworks/LegoContext"

    target 'Tower_Tests' do
    	inherit! :search_paths

    	pod 'Quick', '~> 1.0.0'
        pod 'Nimble', '~> 5.1.1'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
  	end

end
