source 'git@github.com:Limon-O-O/Lego.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'LegoKit_Example' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    

    target 'LegoKit_Tests' do
    	inherit! :search_paths

    	pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  	end

end
